In [6]:
import numpy as np

# a = [[34,32,34,45],[67,78,23.4,45]]
# arr = np.array(a)
# print(arr)
# print(arr.shape) # no. of row and columns
# print(len(arr)) # number of nested values
# print(np.size(arr)) # number of elements
# print(type(arr)) #data type of variable
# print(arr.dtype) # datatype of array
# print(arr.astype(str))# conversion of datatype
# print(arr.astype(int))

arr1 = np.array([33,44,49,43])
arr2 = np.array([30,40,49,43])
print(arr1+arr2)
print(np.add(arr1,arr2))
arr1 = np.array([[33,44],[49,43]])
arr2 = np.array([[30,40],[49,43]])
print(arr1+arr2)



[63 84 98 86]
[63 84 98 86]
[[63 84]
 [98 86]]


In [8]:
arr1 = np.array([33,44,49,43])
arr2 = np.array([30,40,49,43])
print(arr1-arr2)
print(np.subtract(arr1,arr2))
arr1 = np.array([[33,44],[49,43]])
arr2 = np.array([[30,40],[49,43]])
print(arr1-arr2)

[3 4 0 0]
[3 4 0 0]
[[3 4]
 [0 0]]


In [9]:
arr1 = np.array([33,44,49,43])
arr2 = np.array([30,40,49,43])
print(arr1*arr2)
print(np.multiply(arr1,arr2))
arr1 = np.array([[33,44],[49,43]])
arr2 = np.array([[30,40],[49,43]])
print(arr1*arr2)

[ 990 1760 2401 1849]
[ 990 1760 2401 1849]
[[ 990 1760]
 [2401 1849]]


In [10]:
arr1 = np.array([33,44,49,43])
arr2 = np.array([30,40,49,43])
print(arr1/arr2)
print(np.divide(arr1,arr2))
arr1 = np.array([[33,44],[49,43]])
arr2 = np.array([[30,40],[49,43]])
print(arr1/arr2)

[1.1 1.1 1.  1. ]
[1.1 1.1 1.  1. ]
[[1.1 1.1]
 [1.  1. ]]


In [12]:
arr1 = np.array([33,44,49,43])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[1089 1936 2401 1849]


In [15]:
arr1 = np.array([1089, 1936, 2401, 1849])
print(np.sqrt(arr1))

[33. 44. 49. 43.]


In [19]:
# # combining and splitting array
# a = [23,34,23]
# b = [3,45,56]
# print(a+b)

# concatenate

arr1 = np.array([33,44,49,43])
arr2 = np.array([30,40,49,43])
print(np.concatenate([arr1,arr2])) 

[33 44 49 43 30 40 49 43]


In [23]:
arr1 = np.array([[33,44],[49,43]])
arr2 = np.array([[30,40],[49,43]])
print(np.concatenate([arr1,arr2],axis = 0)) 
print(np.concatenate([arr1,arr2],axis = 1)) 

[[33 44]
 [49 43]
 [30 40]
 [49 43]]
[[33 44 30 40]
 [49 43 49 43]]


In [24]:
print(np.hstack([arr1,arr2])) # horizontal concatenation

[[33 44 30 40]
 [49 43 49 43]]


In [ ]:
print(np.vstack([arr1,arr2])) # vertical concatenation concatenation

In [28]:
a = np.array([20,34,45,45,50])
print(np.array_split(a,3))
b = np.array_split(a,3)
print(b[1])

a = np.array([[20,34,45],[45,50,90]])
print(np.array_split(a,3))
b = np.array_split(a,3)
print(b[1])

[array([20, 34]), array([45, 45]), array([50])]
[45 45]
[array([[20, 34, 45]]), array([[45, 50, 90]]), array([], shape=(0, 3), dtype=int32)]
[[45 50 90]]


In [30]:
a = np.array([20,34,45,45,50])
print(np.append(a,90))
a = np.array([[20,34,45],[45,50,90]])
print(np.append(a,90))
print(np.append(a,[100,90]))




[20 34 45 45 50 90]
[20 34 45 45 50 90 90]
[ 20  34  45  45  50  90 100  90]


In [40]:
a = np.array([20,34,45,45,50])
print(np.insert(a,1,50)) # array, index,value
a = np.array([[20,34,45],[45,50,90]])
print(np.insert(a,1,50))
print(np.insert(a,1,[50,60],axis = 1))
# print(np.insert(a,1,[50,60],axis = 0))
a = np.array([[20,34],[45,90]])
print(np.insert(a,1,[50],axis = 0))
print(np.insert(a,[1,2],[50,60],axis = 0))






[20 50 34 45 45 50]
[20 50 34 45 45 50 90]
[[20 50 34 45]
 [45 60 50 90]]
[[20 34]
 [50 50]
 [45 90]]
[[20 34]
 [50 60]
 [45 90]
 [50 60]]


In [45]:
print(a)
print(np.delete(a,1))
print(np.delete(a,1,axis = 0 ))
print(np.delete(a,1,axis = 1 ))

[[20 34]
 [45 90]]
[20 45 90]
[[20 34]]
[[20]
 [45]]


In [ ]:
# function : sort,filter, Search.

In [48]:
# sort function
arr = np.array([34,23,21,-13,45,23,11,67,54,2,1,-1])
print(np.sort(arr))
arr = np.array([[34,23,21,-13,45,23],[11,67,54,2,1,-1]])
print(np.sort(arr))

[-13  -1   1   2  11  21  23  23  34  45  54  67]
[[-13  21  23  23  34  45]
 [ -1   1   2  11  54  67]]


In [63]:
#  search function
arr = np.array([34,23,21,-13,45,23,11,67,54,2,1,-1])
s = np.where(arr ==-13)
print(s)
s = np.where(arr%2 == 0)
print(s)

# searchsorted
arr = np.array([1,2,3,34,45,56,57])
ss = np.searchsorted(arr,44) # gives nearest  element address of the ARRAY!
print(ss)

(array([3], dtype=int64),)
(array([0, 8, 9], dtype=int64),)
4


In [73]:
# filter functon
arr = np.array([34,23,21,-13,45,23,11,67,54,2,1,-1])
fa = [True,False,True,False,True,False,True,False,True,False,True,False]
ga = [False,False,True,False,False,False,True,False,False,False,True,False]
sa = [False,True,False,True,False,True,False,True,False,True,False,True]
new = arr[fa]
new1 = arr[ga]
new2 = arr[sa]
print(new)
print(new1)
print(new2)

fa = arr>34
new = arr[fa]
print(new)
fa = arr%2 == 0
new = arr[fa]
print(new)

[34 21 45 11 54  1]
[21 11  1]
[ 23 -13  23  67   2  -1]
[45 67 54]
[34 54  2]


In [78]:
# Aggregating function

arr = np.array([34,23,21,-13,45,23,11,67,54,2,1,-1])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.size(arr))
print(np.mean(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))


267
-13
67
12
22.25
[ 34  57  78  65 110 133 144 211 265 267 268 267]
[         34         782       16422     -213486    -9606870  -220958010
  1864429186   362703878 -1888827068   517313160   517313160  -517313160]


In [84]:
price = np.array([33,44,49,43,454,34])
quantity = np.array([30,40,49,43,453,567])
print(price,"\n",quantity)
print(np.sum(price))
print(np.cumsum([price,quantity]))
print()
c = (np.cumprod([price,quantity],axis = 0))
print(c)
print(c[1].sum())


[ 33  44  49  43 454  34] 
 [ 30  40  49  43 453 567]
657
[  33   77  126  169  623  657  687  727  776  819 1272 1839]

[[    33     44     49     43    454     34]
 [   990   1760   2401   1849 205662  19278]]
231940


In [ ]:
### ==== statistical function ==== ###

In [95]:
import statistics as stats
baked_food = [133,244,149,143,454,334,130,150]
a = np.array(baked_food)
print(np.mean(a)) # sum of all the values/number of values
# print(np.mean(baked_food))
print(np.median(a)) # central value after sorting
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))



217.125
149.5
133
111.69202914711506
12475.109375


In [98]:
 # -1 represent inversely proportional relationship
# 1 represents proportonal relationship 
# 0 means no relatonship 

tabacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]


print(np.corrcoef([tabacco_consumption,deaths])) # corrcoef : coffecants of corelaton.
# to check dependence of two data in each other by : corrcoef

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [97]:
price = [300,100,350,150,200]
sales = [10,20,7,17,3]

print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
